/* St Edward Lubaga — Food Store Stock Register — app logic (Firebase Firestore + Auth) */
(function(){
"use strict";
const firebaseConfig={apiKey:"AIzaSyCO8JYTdnyZJVBSKGVh8ErEwX1ab4u63w4",authDomain:"sted-food-stock-tracker.firebaseapp.com",projectId:"sted-food-stock-tracker",storageBucket:"sted-food-stock-tracker.firebasestorage.app",messagingSenderId:"76089383749",appId:"1:76089383749:web:9ab325ac4af6aa3d0d7c2c"};
firebase.initializeApp(firebaseConfig); const db=firebase.firestore(), auth=firebase.auth();
try{ db.enablePersistence({synchronizeTabs:true}).catch(e=>console.warn("Offline Firestore persistence unavailable:",e.code||e.message)); }catch(e){console.warn("Offline persistence unavailable",e); }
if("serviceWorker" in navigator){ window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(e=>console.warn("Service worker registration failed",e))); }
const itemsRef=db.collection("items"), stockInRef=db.collection("stockIn"), stockOutRef=db.collection("stockOut"), rolesRef=db.collection("users"), auditRef=db.collection("auditLogs"), suppliersRef=db.collection("suppliers"), approvalsRef=db.collection("stockOutApprovals"), settingsRef=db.collection("settings"), legacyDocRef=db.collection("store").doc("data");
let currentRole="viewer", currentProfile={}, items=[], stockIn=[], stockOut=[], users=[], auditLogs=[], suppliers=[], approvals=[], appSettings={approvalThreshold:100,reportEmail:"",lowStockEmail:"",reportDay:1}; let stockChart=null; const pageState={in:1,out:1,audit:1}; const PAGE_SIZE=25;
let unsub=[];
const $=id=>document.getElementById(id);
function cryptoId(){return Math.random().toString(36).slice(2,10)+Date.now().toString(36);}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));}
function roleLabel(r){return r==="admin"?"Super Admin":r==="staff"?"Staff":"Viewer";}
function canEdit(){return currentRole==="admin"||currentRole==="staff";}
function showStatus(id,msg,error=false){const e=$(id); if(e){e.textContent=msg; e.classList.toggle("error",error);} if(msg)toast(msg,error);}
function toast(msg,error=false){let stack=document.getElementById("toast-stack");if(!stack){stack=document.createElement("div");stack.id="toast-stack";stack.className="toast-stack";document.body.appendChild(stack);}const t=document.createElement("div");t.className="toast"+(error?" error":"");t.textContent=msg;stack.appendChild(t);setTimeout(()=>t.remove(),4200);}
function clearError(){const e=$("shared-note");e.textContent="Connected to the school's live Firestore database.";e.className="note";}
function showError(err){console.error(err);const e=$("shared-note");e.textContent="Database connection/permission error ("+(err?.code||"unknown")+") — please check Firestore rules.";e.className="note error-note";}
function today(){return new Date().toISOString().slice(0,10);}
function money(n){return "UGX " + Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2});}
function dateTime(ts){if(!ts)return "Pending"; try{return ts.toDate().toLocaleString();}catch(e){return String(ts);}}
function getItem(name){return items.find(x=>x.name===name);}
function totals(name, excludeOutId="", excludeInId=""){const inn=stockIn.filter(r=>r.item===name&&r.id!==excludeInId).reduce((s,r)=>s+Number(r.qty||0),0);const out=stockOut.filter(r=>r.item===name&&r.id!==excludeOutId).reduce((s,r)=>s+Number(r.qty||0),0);return {inn,out,balance:inn-out};}
function balance(name,excludeOutId="",excludeInId=""){return totals(name,excludeOutId,excludeInId).balance;}
function applyPermissions(){
 document.querySelectorAll('[data-tab="users"]').forEach(el=>el.style.display=currentRole==="admin"?"":"none");document.querySelectorAll('[data-tab="audit"]').forEach(el=>el.style.display=currentRole==="admin"?"":"none");document.querySelectorAll('[data-tab="approvals"]').forEach(el=>el.style.display=canEdit()?"":"none");
 const edit=canEdit(); document.querySelectorAll("#item-form input,#item-form select,#item-form button,#stockin-form input,#stockin-form select,#stockin-form button,#stockout-form input,#stockout-form select,#stockout-form button").forEach(x=>{if(x.type!=="hidden")x.disabled=!edit;});
 $("current-user-top").textContent=auth.currentUser?`${auth.currentUser.email} • ${roleLabel(currentRole)}`:"";
 $("account-info").innerHTML=auth.currentUser?`<b>${esc(currentProfile.name||"User")}</b><br>${esc(auth.currentUser.email)}<br>Role: <b>${esc(roleLabel(currentRole))}</b><br>Status: ${currentProfile.active===false?"Disabled":"Active"}`:"";
}
async function loadProfile(user){const s=await rolesRef.doc(user.uid).get(); currentProfile=s.exists?s.data():{email:user.email,role:"viewer",active:true}; currentRole=currentProfile.role||"viewer"; if(currentProfile.active===false){await auth.signOut();throw new Error("Account disabled");}applyPermissions();}
async function batchWrites(ref,docs){for(let i=0;i<docs.length;i+=450){const b=db.batch();docs.slice(i,i+450).forEach(d=>b.set(ref.doc(String(d.id||cryptoId())),d));await b.commit();}}
async function migrateLegacy(){
 const [a,b,c]=await Promise.all([itemsRef.limit(1).get(),stockInRef.limit(1).get(),stockOutRef.limit(1).get()]); if(!a.empty||!b.empty||!c.empty)return false;
 try{const s=await legacyDocRef.get(); if(!s.exists)return false; const x=s.data()||{}; const mi=Array.isArray(x.items)?x.items:[], mn=Array.isArray(x.stockIn)?x.stockIn:[], mo=Array.isArray(x.stockOut)?x.stockOut:[]; if(mi.length||mn.length||mo.length){mi.forEach(it=>{if(it.category==null)it.category="";}); await batchWrites(itemsRef,mi); await batchWrites(stockInRef,mn); await batchWrites(stockOutRef,mo); await logAudit("Legacy migration","Moved existing store/data records into separate collections."); return true;}}catch(e){console.warn("Legacy migration unavailable",e);} return false;
}
async function seedIfEmpty(){const s=await itemsRef.limit(1).get();if(!s.empty)return; if(!canEdit())return; const starter=[{id:cryptoId(),name:"Rice",unit:"kg",category:"Cereals",reorder:50},{id:cryptoId(),name:"Posho (Maize Flour)",unit:"kg",category:"Cereals",reorder:100},{id:cryptoId(),name:"Beans",unit:"kg",category:"Legumes",reorder:50},{id:cryptoId(),name:"Cooking Oil",unit:"litre",category:"Oil",reorder:20},{id:cryptoId(),name:"Sugar",unit:"kg",category:"Sugar",reorder:30}]; await batchWrites(itemsRef,starter); await logAudit("System setup","Starter inventory created.");}
async function loadData(){try{await migrateLegacy();await seedIfEmpty();const [is,ins,outs,sups,apps,set]=await Promise.all([itemsRef.get(),stockInRef.get(),stockOutRef.get(),suppliersRef.get(),approvalsRef.orderBy("createdAt","desc").limit(200).get().catch(()=>({docs:[]})),settingsRef.doc("app").get()]);items=is.docs.map(d=>({id:d.id,...d.data()}));stockIn=ins.docs.map(d=>({id:d.id,...d.data()}));stockOut=outs.docs.map(d=>({id:d.id,...d.data()}));suppliers=sups.docs.map(d=>({id:d.id,...d.data()}));approvals=apps.docs.map(d=>({id:d.id,...d.data()}));if(set.exists)appSettings={...appSettings,...set.data()};clearError();renderAll();setupListeners();if(currentRole==="admin")await loadAdminData();}catch(e){showError(e);}}
function setupListeners(){unsub.forEach(f=>f&&f());unsub=[];unsub.push(itemsRef.onSnapshot(s=>{items=s.docs.map(d=>({id:d.id,...d.data()}));renderAll();},showError));unsub.push(stockInRef.onSnapshot(s=>{stockIn=s.docs.map(d=>({id:d.id,...d.data()}));renderAll();},showError));unsub.push(stockOutRef.onSnapshot(s=>{stockOut=s.docs.map(d=>({id:d.id,...d.data()}));renderAll();checkLowStockNotifications();},showError));unsub.push(suppliersRef.onSnapshot(s=>{suppliers=s.docs.map(d=>({id:d.id,...d.data()}));renderAll();},showError));if(canEdit())unsub.push(approvalsRef.orderBy("createdAt","desc").limit(200).onSnapshot(s=>{approvals=s.docs.map(d=>({id:d.id,...d.data()}));renderApprovals();},showError));unsub.push(settingsRef.doc("app").onSnapshot(d=>{if(d.exists)appSettings={...appSettings,...d.data()};renderSettings();},()=>{}));}
async function logAudit(action,details,before=null,after=null){if(!auth.currentUser)return;try{await auditRef.add({uid:auth.currentUser.uid,email:auth.currentUser.email||"",role:currentRole,action:String(action).slice(0,100),details:String(details||"").slice(0,1000),before:before||null,after:after||null,timestamp:firebase.firestore.FieldValue.serverTimestamp()});}catch(e){console.warn("Audit log failed",e);}}
async function loadAdminData(){try{const [us,as]=await Promise.all([rolesRef.get(),auditRef.orderBy("timestamp","desc").limit(200).get()]);users=us.docs.map(d=>({uid:d.id,...d.data()}));auditLogs=as.docs.map(d=>({id:d.id,...d.data()}));renderUsers();renderAudit();}catch(e){showStatus("users-list-status","Could not load users/audit records. Check rules.",true);console.error(e);}}
function renderSummary(){let low=0,inStock=0;items.forEach(it=>{if(balance(it.name)<=Number(it.reorder||0))low++;inStock+=Math.max(0,balance(it.name));});$("summary-strip").innerHTML=`<div class="stat"><div class="num">${items.length}</div><div class="label">Items tracked</div></div><div class="stat ${low?"alert":""}"><div class="num">${low}</div><div class="label">Need restocking</div></div><div class="stat"><div class="num">${stockIn.length}</div><div class="label">Stock In records</div></div><div class="stat"><div class="num">${stockOut.length}</div><div class="label">Stock Out records</div></div><div class="stat"><div class="num">${inStock}</div><div class="label">Units in stock</div></div>`;}
function renderBalance(){const q=$("dashboard-search").value.trim().toLowerCase(),status=$("dashboard-status").value;const rows=items.filter(it=>it.name.toLowerCase().includes(q)||(it.category||"").toLowerCase().includes(q)).filter(it=>status==="all"||(status==="low"?balance(it.name)<=Number(it.reorder||0):balance(it.name)>Number(it.reorder||0)));$("balance-table").querySelector("tbody").innerHTML=rows.length?rows.map(it=>{const t=totals(it.name),low=t.balance<=Number(it.reorder||0);return `<tr><td>${esc(it.name)}</td><td>${esc(it.category||"")}</td><td>${esc(it.unit)}</td><td>${t.inn}</td><td>${t.out}</td><td><b>${t.balance}</b></td><td>${it.reorder}</td><td><span class="badge ${low?"reorder":"ok"}">${low?"RESTOCK":"OK"}</span></td></tr>`}).join(""):`<tr><td colspan="8" class="empty">No matching items.</td></tr>`;}
function renderItems(){const q=$("items-search").value.trim().toLowerCase();const rows=items.filter(it=>it.name.toLowerCase().includes(q)||(it.category||"").toLowerCase().includes(q));$("items-table").querySelector("tbody").innerHTML=rows.length?rows.map(it=>{const bal=balance(it.name),low=bal<=Number(it.reorder||0);return `<tr><td>${esc(it.name)}</td><td>${esc(it.category||"")}</td><td>${esc(it.unit)}</td><td>${Number(it.reorder||0)}</td><td>${bal}</td><td><span class="badge ${low?"reorder":"ok"}">${low?"RESTOCK":"OK"}</span></td><td>${canEdit()?`<button class="secondary" data-edit-item="${esc(it.id)}">Edit</button> `:""}${currentRole==="admin"?`<button class="secondary danger" data-delete-item="${esc(it.id)}">Delete</button>`:""}${!canEdit()?"—":""}</td></tr>`}).join(""):`<tr><td colspan="7" class="empty">No items found.</td></tr>`;document.querySelectorAll("[data-edit-item]").forEach(b=>b.onclick=()=>editItem(b.dataset.editItem));document.querySelectorAll("[data-delete-item]").forEach(b=>b.onclick=()=>deleteItem(b.dataset.deleteItem));}
function itemOptions(sel,cur=""){const opts=`<option value="">Select item…</option>`+items.map(it=>`<option value="${esc(it.name)}">${esc(it.name)} (${esc(it.unit)})</option>`).join("");$(sel).innerHTML=opts;if(cur)$(sel).value=cur;}
function filterTx(list,prefix){const q=$(prefix+"-search").value.trim().toLowerCase(),from=$(prefix+"-from").value,to=$(prefix==="out"?"out-to-date":prefix+"-to").value;return list.filter(r=>(!from||r.date>=from)&&(!to||r.date<=to)&&(!q||[r.item,r.supplier,r.by,r.to,r.notes].join(" ").toLowerCase().includes(q))).sort((a,b)=>(b.date||"").localeCompare(a.date||""));}
function pagerHtml(prefix,total){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));pageState[prefix]=Math.min(pageState[prefix]||1,pages);return `<div class="pager"><button class="secondary" data-page="${prefix}" data-dir="-1" ${pageState[prefix]<=1?"disabled":""}>Previous</button><span>Page ${pageState[prefix]} of ${pages} • ${total} records</span><button class="secondary" data-page="${prefix}" data-dir="1" ${pageState[prefix]>=pages?"disabled":""}>Next</button></div>`}
function bindPager(){document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{pageState[b.dataset.page]+=Number(b.dataset.dir);renderAll();});}
function renderStockIn(){const all=filterTx(stockIn,"in"),start=(pageState.in-1)*PAGE_SIZE,rows=all.slice(start,start+PAGE_SIZE);const tbody=$("stockin-table").querySelector("tbody");tbody.innerHTML=rows.length?rows.map(r=>{const exp=r.expiry?new Date(r.expiry+"T00:00:00"):null,soon=exp&&((exp-new Date())/86400000)<=30;return `<tr><td>${esc(r.date)}</td><td>${esc(r.item)}</td><td>${Number(r.qty||0)}</td><td>${esc(r.supplier)}</td><td>${esc(r.batch||"")}</td><td class="${soon?"warn":""}">${esc(r.expiry||"")}</td><td>${esc(r.by)}</td><td>${esc(r.notes)}</td><td>${canEdit()?`<button class="secondary" data-edit-in="${esc(r.id)}">Edit</button> `:""}${currentRole==="admin"?`<button class="secondary danger" data-delete-in="${esc(r.id)}">Delete</button>`:""}${!canEdit()?"—":""}</td></tr>`}).join(""):`<tr><td colspan="9" class="empty">No matching Stock In records.</td></tr>`;let p=$("stockin-table").parentElement.querySelector(".pager");if(p)p.remove();$("stockin-table").parentElement.insertAdjacentHTML("beforeend",pagerHtml("in",all.length));document.querySelectorAll("[data-edit-in]").forEach(b=>b.onclick=()=>editIn(b.dataset.editIn));document.querySelectorAll("[data-delete-in]").forEach(b=>b.onclick=()=>deleteIn(b.dataset.deleteIn));bindPager();}
function renderStockOut(){const all=filterTx(stockOut,"out"),start=(pageState.out-1)*PAGE_SIZE,rows=all.slice(start,start+PAGE_SIZE);$("stockout-table").querySelector("tbody").innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.item)}</td><td>${Number(r.qty||0)}</td><td>${esc(r.to)}</td><td>${esc(r.by)}</td><td>${esc(r.notes)}</td><td>${canEdit()?`<button class="secondary" data-edit-out="${esc(r.id)}">Edit</button> `:""}${currentRole==="admin"?`<button class="secondary danger" data-delete-out="${esc(r.id)}">Delete</button>`:""}${!canEdit()?"—":""}</td></tr>`).join(""):`<tr><td colspan="7" class="empty">No matching Stock Out records.</td></tr>`;let p=$("stockout-table").parentElement.querySelector(".pager");if(p)p.remove();$("stockout-table").parentElement.insertAdjacentHTML("beforeend",pagerHtml("out",all.length));document.querySelectorAll("[data-edit-out]").forEach(b=>b.onclick=()=>editOut(b.dataset.editOut));document.querySelectorAll("[data-delete-out]").forEach(b=>b.onclick=()=>deleteOut(b.dataset.deleteOut));bindPager();}
function renderUsers(){const q=$("users-search").value.trim().toLowerCase();const rows=users.filter(u=>(u.name||"").toLowerCase().includes(q)||(u.email||"").toLowerCase().includes(q));$("users-table").querySelector("tbody").innerHTML=rows.length?rows.map(u=>`<tr><td>${esc(u.name||"")}</td><td>${esc(u.email||"")}</td><td>${esc(roleLabel(u.role))}</td><td><span class="badge ${u.active===false?"reorder":"ok"}">${u.active===false?"Disabled":"Active"}</span></td><td>${esc(u.createdAt||"")}</td><td><button class="secondary" data-reset-user="${esc(u.uid)}">Send reset</button> <button class="secondary" data-toggle-user="${esc(u.uid)}">${u.active===false?"Enable":"Disable"}</button></td></tr>`).join(""):`<tr><td colspan="6" class="empty">No users found.</td></tr>`;document.querySelectorAll("[data-reset-user]").forEach(b=>b.onclick=()=>resetUser(b.dataset.resetUser));document.querySelectorAll("[data-toggle-user]").forEach(b=>b.onclick=()=>toggleUser(b.dataset.toggleUser));}
function renderAudit(){const q=$("audit-search").value.trim().toLowerCase();const all=auditLogs.filter(a=>[a.email,a.action,a.details,JSON.stringify(a.before||{}),JSON.stringify(a.after||{})].join(" ").toLowerCase().includes(q)),start=(pageState.audit-1)*PAGE_SIZE,rows=all.slice(start,start+PAGE_SIZE);$("audit-table").querySelector("tbody").innerHTML=rows.length?rows.map(a=>`<tr><td>${esc(dateTime(a.timestamp))}</td><td>${esc(a.email)}</td><td>${esc(roleLabel(a.role))}</td><td>${esc(a.action)}</td><td>${esc(a.details)}</td><td><code>${esc(a.before?JSON.stringify(a.before):"")}</code></td><td><code>${esc(a.after?JSON.stringify(a.after):"")}</code></td></tr>`).join(""):`<tr><td colspan="7" class="empty">No audit activity.</td></tr>`;let p=$("audit-table").parentElement.querySelector(".pager");if(p)p.remove();$("audit-table").parentElement.insertAdjacentHTML("beforeend",pagerHtml("audit",all.length));bindPager();}
function renderAll(){renderSummary();renderBalance();renderItems();itemOptions("in-item",$("in-item").value);itemOptions("out-item",$("out-item").value);supplierOptions();renderStockIn();renderStockOut();renderSuppliers();renderApprovals();renderUsers();renderAudit();updatePreview();renderTrendChart();renderSettings();}
function resetItemForm(){$("item-form").reset();$("item-id").value="";$("item-form-title").textContent="Add / update an item";$("item-save-btn").textContent="Save item";$("item-cancel-btn").style.display="none";}
function editItem(id){if(!canEdit())return alert("Only Staff or Super Admin can edit items.");const it=items.find(x=>x.id===id);if(!it)return;$("item-id").value=id;$("item-name").value=it.name;$("item-unit").value=it.unit;$("item-category").value=it.category||"";$("item-reorder").value=it.reorder||0;$("item-form-title").textContent="Edit item";$("item-save-btn").textContent="Update item";$("item-cancel-btn").style.display="inline-block";go("items");window.scrollTo({top:0,behavior:"smooth"});}
async function deleteItem(id){if(currentRole!=="admin")return alert("Only Super Admin can delete items.");const it=items.find(x=>x.id===id);if(!it)return;if(stockIn.some(r=>r.item===it.name)||stockOut.some(r=>r.item===it.name))return alert("This item has stock history. Do not delete it; edit its details instead.");if(!confirm(`Delete ${it.name}? This cannot be undone.`))return;try{await itemsRef.doc(id).delete();await logAudit("Item deleted",`Item: ${it.name}`);}catch(e){showStatus("item-status","Could not delete item.",true);}}
async function deleteTx(type,id){if(currentRole!=="admin")return alert("Only Super Admin can delete stock records.");const ref=type==="in"?stockInRef:stockOutRef;const arr=type==="in"?stockIn:stockOut;const r=arr.find(x=>x.id===id);if(!r)return;if(!confirm(`Delete this ${type==="in"?"Stock In":"Stock Out"} record for ${r.item}, quantity ${r.qty}?`))return;try{await ref.doc(id).delete();await logAudit(type==="in"?"Stock In deleted":"Stock Out deleted",`Item: ${r.item}; Quantity: ${r.qty}; Date: ${r.date}`);}catch(e){showError(e);}}
function editIn(id){if(!canEdit())return;const r=stockIn.find(x=>x.id===id);if(!r)return;$("in-id").value=id;$("in-date").value=r.date;itemOptions("in-item",r.item);$("in-qty").value=r.qty;supplierOptions(r.supplier||"");$("in-batch").value=r.batch||"";$("in-expiry").value=r.expiry||"";$("in-by").value=r.by||"";$("in-notes").value=r.notes||"";$("in-form-title").textContent="Edit Stock In";$("in-save-btn").textContent="Update Stock In";$("in-cancel-btn").style.display="inline-block";go("stockin");window.scrollTo({top:0,behavior:"smooth"});}
function editOut(id){if(!canEdit())return;const r=stockOut.find(x=>x.id===id);if(!r)return;$("out-id").value=id;$("out-date").value=r.date;itemOptions("out-item",r.item);$("out-qty").value=r.qty;$("out-to").value=r.to||"";$("out-by").value=r.by||"";$("out-notes").value=r.notes||"";$("out-form-title").textContent="Edit Stock Out";$("out-save-btn").textContent="Update Stock Out";$("out-cancel-btn").style.display="inline-block";go("stockout");window.scrollTo({top:0,behavior:"smooth"});}
async function deleteIn(id){await deleteTx("in",id);} async function deleteOut(id){await deleteTx("out",id);}
function resetIn(){$("stockin-form").reset();$("in-id").value="";$("in-date").value=today();$("in-form-title").textContent="Record Stock In";$("in-save-btn").textContent="Save Stock In";$("in-cancel-btn").style.display="none";itemOptions("in-item");}
function resetOut(){$("stockout-form").reset();$("out-id").value="";$("out-date").value=today();$("out-form-title").textContent="Record Stock Out";$("out-save-btn").textContent="Save Stock Out";$("out-cancel-btn").style.display="none";itemOptions("out-item");}
function go(tab){document.querySelectorAll(".tab,.side-link").forEach(t=>t.classList.toggle("active",t.dataset.tab===tab));document.querySelectorAll(".panel").forEach(p=>p.classList.toggle("active",p.id==="panel-"+tab));const active=document.querySelector('.side-link[data-tab="'+tab+'"]')||document.querySelector('.tab[data-tab="'+tab+'"]');if($("page-title"))$("page-title").textContent=active?active.textContent.trim():tab;window.scrollTo({top:0,behavior:"instant"in window?"instant":"auto"});}
function dateInRange(d,from,to){return (!from||d>=from)&&(!to||d<=to);}
function filteredReports(){const from=$("report-from").value,to=$("report-to").value;return {from,to,ins:stockIn.filter(r=>dateInRange(r.date||"",from,to)),outs:stockOut.filter(r=>dateInRange(r.date||"",from,to))};}
function monthlyRows(ins,outs){const m={};[...ins.map(r=>({...r,t:"in"})),...outs.map(r=>({...r,t:"out"}))].forEach(r=>{const k=(r.date||"").slice(0,7)||"Unknown";m[k] ||= {inQty:0,outQty:0,inTx:0,outTx:0};if(r.t==="in"){m[k].inQty+=Number(r.qty||0);m[k].inTx++;}else{m[k].outQty+=Number(r.qty||0);m[k].outTx++;}});return Object.keys(m).sort().map(k=>[k,m[k].inQty,m[k].outQty,m[k].inQty-m[k].outQty,m[k].inTx,m[k].outTx]);}
function categoryRows(ins,outs){return [...new Set(items.map(i=>i.category||"Uncategorised"))].sort().map(cat=>{const names=items.filter(i=>(i.category||"Uncategorised")===cat).map(i=>i.name),i=ins.filter(r=>names.includes(r.item)).reduce((s,r)=>s+Number(r.qty||0),0),o=outs.filter(r=>names.includes(r.item)).reduce((s,r)=>s+Number(r.qty||0),0);return [cat,names.length,i,o,i-o];});}
function updatePreview(){if(!$("report-preview-content"))return;const {from,to,ins,outs}=filteredReports();const low=items.filter(it=>balance(it.name)<=Number(it.reorder||0));$("report-preview-content").innerHTML=`<div class="report-cards"><div><b>Period</b><br>${esc(from||"All dates")} → ${esc(to||"All dates")}</div><div><b>Stock In</b><br>${ins.length} records / ${ins.reduce((s,r)=>s+Number(r.qty||0),0)} units</div><div><b>Stock Out</b><br>${outs.length} records / ${outs.reduce((s,r)=>s+Number(r.qty||0),0)} units</div><div><b>Low stock</b><br>${low.length} items</div></div><h3>Monthly summary</h3><div class="table-wrap"><table><thead><tr><th>Month</th><th>In</th><th>Out</th><th>Net</th><th>In Tx</th><th>Out Tx</th></tr></thead><tbody>${monthlyRows(ins,outs).map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join("")}</tr>`).join("")||'<tr><td colspan="6" class="empty">No transactions in this period.</td></tr>'}</tbody></table></div><h3 style="margin-top:18px">Category breakdown</h3><div class="table-wrap"><table><thead><tr><th>Category</th><th>Items</th><th>In</th><th>Out</th><th>Net</th></tr></thead><tbody>${categoryRows(ins,outs).map(r=>`<tr><td>${esc(r[0])}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td></tr>`).join("")}</tbody></table></div>`;}
function exportExcel(){
  try{
    if(typeof XLSX==="undefined") throw new Error("Excel library not loaded");
    const {from,to,ins,outs}=filteredReports();
    const wb=XLSX.utils.book_new();
    const type=$("report-type").value;
    const inv=[["Item","Category","Unit","Stock In","Stock Out","Balance","Reorder Level","Status"]];
    items.forEach(it=>{const t=totals(it.name);inv.push([it.name,it.category||"",it.unit,t.inn,t.out,t.balance,it.reorder,t.balance<=Number(it.reorder||0)?"RESTOCK":"OK"]);});
    const si=[["ID","Date","Item","Quantity","Supplier","Batch","Expiry","Received By","Notes"]];
    ins.forEach(r=>si.push([r.id,r.date,r.item,r.qty,r.supplier||"",r.batch||"",r.expiry||"",r.by||"",r.notes||""]));
    const so=[["ID","Date","Item","Quantity","Issued To","Issued By","Notes"]];
    outs.forEach(r=>so.push([r.id,r.date,r.item,r.qty,r.to||"",r.by||"",r.notes||""]));
    const mon=[["Month","Stock In Qty","Stock Out Qty","Net Movement","Stock In Tx","Stock Out Tx"],...monthlyRows(ins,outs)]; const cat=[["Category","Items","Stock In","Stock Out","Net"],...categoryRows(ins,outs)];
    const summary=[["St Edward High School Lubaga Food Store Report"],["Generated",new Date().toLocaleString()],["From",from||"All dates"],["To",to||"All dates"],["Items",items.length],["Items in Stock (units)",items.reduce((s,it)=>s+Math.max(0,balance(it.name)),0)],["Low Stock Items",items.filter(it=>balance(it.name)<=Number(it.reorder||0)).length],["Stock In Records",ins.length],["Stock Out Records",outs.length]];
    if(type==="all"||type==="inventory") XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(inv),"Inventory");
    if(type==="all"||type==="stockin") XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(si),"Stock In");
    if(type==="all"||type==="stockout") XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(so),"Stock Out");
    if(type==="all"||type==="monthly") XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(mon),"Monthly Summary"); if(type==="all"||type==="category") XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(cat),"Categories");
    XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(summary),"Summary");
    if(currentRole==="admin"){
      const userRows=[["Name","Email","Role","Status","Created"],...users.map(u=>[u.name||"",u.email||"",roleLabel(u.role),u.active===false?"Disabled":"Active",u.createdAt||""] )];
      const auditRows=[["Date/Time","Email","Role","Action","Details","Before","After","UID"],...auditLogs.map(a=>[dateTime(a.timestamp),a.email||"",roleLabel(a.role),a.action||"",a.details||"",a.before?JSON.stringify(a.before):"",a.after?JSON.stringify(a.after):"",a.uid||""] )];
      XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(userRows),"Users");
      XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(auditRows),"Audit Log");
    }
    XLSX.writeFile(wb,`St-Edward-Food-Store-${today()}.xlsx`);
    showStatus("report-status","Excel report exported successfully.");
    logAudit("Report exported","Excel report generated.");
  }catch(e){console.error(e);showStatus("report-status","Could not export Excel. Make sure the page has loaded fully.",true);}
}
function printReport(){updatePreview();const html=$("report-preview").innerHTML;const w=window.open("","_blank");if(!w)return alert("Please allow pop-ups for this site.");w.document.write(`<html><head><title>St Edward Food Store Report</title><style>body{font-family:Arial,sans-serif;padding:30px;color:#222}h2,h3{color:#24402f}table{width:100%;border-collapse:collapse;margin-top:15px}th,td{border:1px solid #ccc;padding:7px;text-align:left}.report-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.report-cards>div{border:1px solid #ccc;padding:10px}@media print{button{display:none}}</style></head><body><h1>St Edward High School Lubaga</h1><p>Food Store Report — ${new Date().toLocaleString()}</p>${html}
<footer style="margin-top:30px;border-top:1px solid #ccc;padding-top:12px">© 2026 Marvin Marvel. All rights reserved.</footer></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300);logAudit("Report printed","PDF-ready report opened for printing.");}
async function saveItem(e){e.preventDefault();if(!canEdit())return showStatus("item-status","Only Staff and Super Admin can edit items.",true);const id=$("item-id").value,name=$("item-name").value.trim(),unit=$("item-unit").value.trim(),category=$("item-category").value.trim(),reorder=Number($("item-reorder").value);if(!name||!unit||reorder<0)return showStatus("item-status","Enter valid item details.",true);if(items.some(it=>it.name.toLowerCase()===name.toLowerCase()&&it.id!==id))return showStatus("item-status","That item already exists.",true);const before=id?(items.find(x=>x.id===id)||null):null;const data={id:id||cryptoId(),name,unit,category,reorder,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};try{await itemsRef.doc(data.id).set(data,{merge:true});await logAudit(id?"Item updated":"Item added",`Item: ${name}; Reorder: ${reorder}`,before,data);resetItemForm();showStatus("item-status",id?"Item updated successfully.":"Item added successfully.");}catch(e){showError(e);}}
async function saveIn(e){e.preventDefault();if(!canEdit())return showStatus("stockin-status","Only Staff and Super Admin can record stock in.",true);const id=$("in-id").value,date=$("in-date").value,item=$("in-item").value,qty=Number($("in-qty").value);if(!date||!item||qty<=0)return showStatus("stockin-status","Enter date, item and a quantity greater than zero.",true);const before=id?(stockIn.find(x=>x.id===id)||null):null;const r={id:id||cryptoId(),date,item,qty,supplier:$("in-supplier").value,batch:$("in-batch").value.trim(),expiry:$("in-expiry").value,by:$("in-by").value.trim(),notes:$("in-notes").value.trim(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};try{await stockInRef.doc(r.id).set(r,{merge:true});await logAudit(id?"Stock In updated":"Stock In recorded",`Item: ${item}; Quantity: ${qty}; Supplier: ${r.supplier}`,before,r);resetIn();showStatus("stockin-status",id?"Stock In updated.":"Stock In saved.");}catch(e){showError(e);}}
async function saveOut(e){e.preventDefault();if(!canEdit())return showStatus("stockout-status","Only Staff and Super Admin can record stock out.",true);const id=$("out-id").value,date=$("out-date").value,item=$("out-item").value,qty=Number($("out-qty").value);if(!date||!item||qty<=0)return showStatus("stockout-status","Enter date, item and a quantity greater than zero.",true);const available=balance(item,"",id);if(qty>available+1e-9)return showStatus("stockout-status",`Not enough stock. Available ${available} ${getItem(item)?.unit||"units"}.`,true);const before=id?(stockOut.find(x=>x.id===id)||null):null;const r={id:id||cryptoId(),date,item,qty,to:$("out-to").value.trim(),by:$("out-by").value.trim(),notes:$("out-notes").value.trim(),createdBy:auth.currentUser.uid,createdByEmail:auth.currentUser.email||"",updatedAt:firebase.firestore.FieldValue.serverTimestamp()};try{if(!id&&qty>Number(appSettings.approvalThreshold||100)){await approvalsRef.doc(r.id).set({...r,status:"pending",createdAt:firebase.firestore.FieldValue.serverTimestamp()});await logAudit("Stock Out approval requested",`Item: ${item}; Quantity: ${qty}; Threshold: ${appSettings.approvalThreshold}`,null,r);resetOut();showStatus("stockout-status","Large Stock Out submitted for second-person approval.");}else{await stockOutRef.doc(r.id).set(r,{merge:true});await logAudit(id?"Stock Out updated":"Stock Out recorded",`Item: ${item}; Quantity: ${qty}; Issued to: ${r.to}`,before,r);resetOut();showStatus("stockout-status",id?"Stock Out updated.":"Stock Out saved.");}}catch(e){showError(e);}}
async function createUser(e){e.preventDefault();if(currentRole!=="admin")return showStatus("user-status","Only Super Admin can create users.",true);const name=$("user-name").value.trim(),email=$("user-email").value.trim(),password=$("user-password").value,role=$("user-role").value;if(password.length<6)return showStatus("user-status","Password must be at least 6 characters.",true);try{const n="userCreationApp";let app;try{app=firebase.app(n);}catch(x){app=firebase.initializeApp(firebaseConfig,n);}const sa=app.auth(),cred=await sa.createUserWithEmailAndPassword(email,password);await rolesRef.doc(cred.user.uid).set({name,email,role,active:true,createdAt:new Date().toISOString().slice(0,10)});await cred.user.sendEmailVerification().catch(()=>{});await logAudit("User created",`Name: ${name}; Email: ${email}; Role: ${roleLabel(role)}`);await sa.signOut();e.target.reset();showStatus("user-status",`User created. Verification email sent to ${email}.`);await loadAdminData();}catch(e){console.error(e);showStatus("user-status",e.code?`Could not create user: ${e.code}`:"Could not create user.",true);}}
async function resetUser(uid){if(currentRole!=="admin")return;const u=users.find(x=>x.uid===uid);if(!u)return;if(!confirm(`Send a password reset email to ${u.email}?`))return;try{await auth.sendPasswordResetEmail(u.email);await logAudit("Password reset requested",`Email: ${u.email}`);alert("Password reset email sent.");}catch(e){alert("Could not send reset email: "+(e.code||"error"));}}
async function toggleUser(uid){if(currentRole!=="admin")return; if(uid===auth.currentUser.uid)return alert("You cannot disable your own account here.");const u=users.find(x=>x.uid===uid);if(!u)return;const active=u.active===false; if(!confirm(`${active?"Enable":"Disable"} ${u.email}?`))return;try{await rolesRef.doc(uid).update({active});await logAudit(active?"User enabled":"User disabled",`Email: ${u.email}`);await loadAdminData();}catch(e){alert("Could not update user status.");}}
async function changePassword(e){e.preventDefault();const a=$("new-password").value,b=$("confirm-password").value;if(a.length<6||a!==b)return showStatus("password-status","Passwords must match and contain at least 6 characters.",true);try{await auth.currentUser.updatePassword(a);e.target.reset();showStatus("password-status","Password changed successfully.");await logAudit("Password changed","User changed their own password.");}catch(e){showStatus("password-status",e.code==="auth/requires-recent-login"?"For security, sign out and sign in again, then change the password.":"Could not change password.",true);}}


function supplierOptions(cur=""){const e=$("in-supplier");if(!e)return;e.innerHTML='<option value="">Select supplier…</option>'+suppliers.sort((a,b)=>(a.name||"").localeCompare(b.name||"")).map(s=>`<option value="${esc(s.name)}">${esc(s.name)}</option>`).join("");if(cur)e.value=cur;}
function renderSuppliers(){const t=$("suppliers-table");if(!t)return;t.querySelector("tbody").innerHTML=suppliers.length?suppliers.map(s=>{const rows=stockIn.filter(r=>r.supplier===s.name);return `<tr><td>${esc(s.name)}</td><td>${esc(s.phone||"")}</td><td>${esc(s.email||"")}</td><td>${rows.length}</td><td>${rows.reduce((a,r)=>a+Number(r.qty||0),0)}</td><td>${canEdit()?`<button class="secondary" data-edit-supplier="${s.id}">Edit</button>`:"—"}</td></tr>`}).join(""):'<tr><td colspan="6" class="empty">No suppliers yet.</td></tr>';document.querySelectorAll('[data-edit-supplier]').forEach(b=>b.onclick=()=>{const x=suppliers.find(s=>s.id===b.dataset.editSupplier);if(!x)return;$("supplier-id").value=x.id;$("supplier-name").value=x.name||"";$("supplier-phone").value=x.phone||"";$("supplier-email").value=x.email||"";$("supplier-notes").value=x.notes||"";});}
async function saveSupplier(e){e.preventDefault();if(!canEdit())return showStatus("supplier-status","Only Staff or Super Admin can edit suppliers.",true);const id=$("supplier-id").value||cryptoId(),before=suppliers.find(x=>x.id===id)||null,data={name:$("supplier-name").value.trim(),phone:$("supplier-phone").value.trim(),email:$("supplier-email").value.trim(),notes:$("supplier-notes").value.trim(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(!data.name)return;await suppliersRef.doc(id).set(data,{merge:true});await logAudit(before?"Supplier updated":"Supplier added",`Supplier: ${data.name}`,before,data);e.target.reset();$("supplier-id").value="";showStatus("supplier-status","Supplier saved.");}
function renderApprovals(){const t=$("approvals-table");if(!t)return;t.querySelector("tbody").innerHTML=approvals.length?approvals.map(a=>`<tr><td>${esc(a.date||"")}</td><td>${esc(a.item||"")}</td><td>${Number(a.qty||0)}</td><td>${esc(a.createdByEmail||a.createdBy||"")}</td><td>${esc(a.to||"")}</td><td><span class="badge ${a.status==="pending"?"reorder":"ok"}">${esc(a.status||"pending")}</span></td><td>${a.status==="pending"&&a.createdBy!==auth.currentUser?.uid&&canEdit()?`<button data-approve="${a.id}">Approve</button> <button class="secondary danger" data-reject="${a.id}">Reject</button>`:"—"}</td></tr>`).join(""):'<tr><td colspan="7" class="empty">No approval requests.</td></tr>';document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approveOut(b.dataset.approve,true));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>approveOut(b.dataset.reject,false));}
async function approveOut(id,ok){const a=approvals.find(x=>x.id===id);if(!a||a.createdBy===auth.currentUser.uid)return alert("A different user must approve this request.");if(ok&&Number(a.qty)>balance(a.item)+1e-9)return alert("Stock is no longer sufficient for this request.");const batch=db.batch(),ref=approvalsRef.doc(id);if(ok){const out={...a,status:undefined,createdAt:undefined,approvedBy:auth.currentUser.uid,approvedByEmail:auth.currentUser.email||"",approvedAt:firebase.firestore.FieldValue.serverTimestamp(),approvalId:id};delete out.status;delete out.createdAt;batch.set(stockOutRef.doc(id),out,{merge:true});batch.update(ref,{status:"approved",approvedBy:auth.currentUser.uid,approvedByEmail:auth.currentUser.email||"",approvedAt:firebase.firestore.FieldValue.serverTimestamp()});}else batch.update(ref,{status:"rejected",approvedBy:auth.currentUser.uid,approvedByEmail:auth.currentUser.email||"",approvedAt:firebase.firestore.FieldValue.serverTimestamp()});await batch.commit();await logAudit(ok?"Stock Out approved":"Stock Out rejected",`Item: ${a.item}; Quantity: ${a.qty}`,a,{...a,status:ok?"approved":"rejected"});}
function renderSettings(){if($("approval-threshold"))$("approval-threshold").value=Number(appSettings.approvalThreshold||100);if($("report-email"))$("report-email").value=appSettings.reportEmail||"";if($("low-stock-email"))$("low-stock-email").value=appSettings.lowStockEmail||"";if($("report-day"))$("report-day").value=Number(appSettings.reportDay||1);}
async function saveSettings(part){if(currentRole!=="admin")return alert("Only Super Admin can change system settings.");await settingsRef.doc("app").set(part,{merge:true});await logAudit("System settings updated",Object.keys(part).join(", "),appSettings,{...appSettings,...part});}
function trendData(){const rows=[...items].sort((a,b)=>a.name.localeCompare(b.name));return {labels:rows.map(i=>i.name),values:rows.map(i=>balance(i.name))};}
function renderTrendChart(){const c=$("stock-balance-chart");if(!c||typeof Chart==="undefined")return;const d=trendData();if(stockChart)stockChart.destroy();stockChart=new Chart(c,{type:"bar",data:{labels:d.labels,datasets:[{label:"Balance",data:d.values}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}});}
async function checkLowStockNotifications(){const low=items.filter(i=>balance(i.name)<=Number(i.reorder||0));if(low.length)sendLowStockEmail(low);if(!("Notification" in window)||Notification.permission!=="granted")return;if(!low.length)return;const key="lowStockNotice:"+today(),sig=low.map(i=>i.id).sort().join(",");if(localStorage.getItem(key)===sig)return;new Notification("Food Store low-stock alert",{body:low.slice(0,5).map(i=>`${i.name}: ${balance(i.name)} ${i.unit}`).join(" • ")+(low.length>5?` • +${low.length-5} more`:"")});localStorage.setItem(key,sig);}
async function enableNotifications(){if(!("Notification" in window))return alert("This browser does not support notifications.");const p=await Notification.requestPermission();if(p==="granted"){await checkLowStockNotifications();alert("Low-stock browser notifications enabled.");}}
async function importBulk(){if(!canEdit())return;const f=$("bulk-file").files[0];if(!f)return alert("Choose a CSV or Excel file first.");const buf=await f.arrayBuffer(),wb=XLSX.read(buf),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""});let count=0;for(const row of rows){const name=String(row.Item||row.item||row.Name||"").trim();if(!name)continue;const existing=items.find(i=>i.name.toLowerCase()===name.toLowerCase());const data={id:existing?.id||cryptoId(),name,unit:String(row.Unit||row.unit||"unit").trim(),category:String(row.Category||row.category||"").trim(),reorder:Number(row.Reorder||row.reorder||0),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};await itemsRef.doc(data.id).set(data,{merge:true});count++;}await logAudit("Bulk import",`${count} items imported from ${f.name}`);alert(`${count} items imported.`);$("bulk-file").value="";}

// events
document.querySelectorAll(".tab,.side-link").forEach(t=>t.onclick=()=>go(t.dataset.tab));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
$("item-form").onsubmit=saveItem;$("supplier-form").onsubmit=saveSupplier;$("stockin-form").onsubmit=saveIn;$("stockout-form").onsubmit=saveOut;$("user-form").onsubmit=createUser;$("change-password-form").onsubmit=changePassword;
$("item-cancel-btn").onclick=resetItemForm;$("in-cancel-btn").onclick=resetIn;$("out-cancel-btn").onclick=resetOut;$("export-excel-btn").onclick=exportExcel;$("print-report-btn").onclick=printReport;$("refresh-btn").onclick=()=>loadData();$("notify-btn").onclick=enableNotifications;$("bulk-import-btn").onclick=importBulk;$("save-threshold").onclick=()=>saveSettings({approvalThreshold:Number($("approval-threshold").value||100)});$("save-report-settings").onclick=()=>saveSettings({reportEmail:$("report-email").value.trim(),lowStockEmail:$("low-stock-email").value.trim(),reportDay:Number($("report-day").value||1)});
["dashboard-search","dashboard-status","items-search","in-search","in-from","in-to","out-search","out-from","out-to-date","report-from","report-to","report-type","users-search","audit-search"].forEach(id=>$(id).addEventListener("input",renderAll));
$("signout-btn").onclick=()=>auth.signOut();$("dark-toggle").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("foodStoreDark",document.body.classList.contains("dark")?"1":"0");renderTrendChart();};if(localStorage.getItem("foodStoreDark")==="1")document.body.classList.add("dark");
$("forgot-password-btn").onclick=async()=>{const email=$("login-email").value.trim();if(!email)return showStatus("login-status","Enter your email first.",true);try{await auth.sendPasswordResetEmail(email);showStatus("login-status","Password reset email sent.");}catch(e){showStatus("login-status","Could not send reset email. Check the email.",true);}};

const loginScreen=$("login-screen"),appContent=$("app-content");auth.onAuthStateChanged(async user=>{if(!user){currentRole="viewer";currentProfile={};loginScreen.style.display="flex";appContent.style.display="none";unsub.forEach(f=>f&&f());unsub=[];return;}try{await loadProfile(user);loginScreen.style.display="none";appContent.style.display="block";$("in-date").value=today();$("out-date").value=today();await loadData();applyPermissions();}catch(e){console.error(e);showStatus("login-status",e.message==="Account disabled"?"This account is disabled.":"Could not load your account.",true);await auth.signOut();}});
$("login-form").onsubmit=async e=>{e.preventDefault();try{await auth.signInWithEmailAndPassword($("login-email").value.trim(),$("login-password").value);}catch(err){showStatus("login-status",err.code==="auth/invalid-credential"?"Sign-in failed — check your email and password.":"Sign-in failed. Check your details.",true);}};
$("report-from").value=new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10);$("report-to").value=today();

/* ---------- Added: real PDF export (in addition to browser Print/Save-PDF) ---------- */
function exportPDF(){
  try{
    if(typeof window.jspdf==="undefined")throw new Error("PDF library not loaded");
    updatePreview();
    const {jsPDF}=window.jspdf;
    const doc=new jsPDF({unit:"pt"});
    const {from,to,ins,outs}=filteredReports();
    const low=items.filter(it=>balance(it.name)<=Number(it.reorder||0));
    let y=48;
    doc.setFont("helvetica","bold");doc.setFontSize(16);doc.text("St Edward High School Lubaga",40,y);
    y+=20;doc.setFontSize(12);doc.text("Food Store Report",40,y);
    y+=16;doc.setFont("helvetica","normal");doc.setFontSize(10);
    doc.text(`Generated ${new Date().toLocaleString()} — Period: ${from||"All dates"} to ${to||"All dates"}`,40,y);
    y+=22;
    const summaryRows=[
      ["Items tracked",String(items.length)],
      ["Units in stock",String(items.reduce((s,it)=>s+Math.max(0,balance(it.name)),0))],
      ["Low stock items",String(low.length)],
      ["Stock In records",String(ins.length)],
      ["Stock Out records",String(outs.length)]
    ];
    doc.autoTable({startY:y,head:[["Summary","Value"]],body:summaryRows,theme:"grid",styles:{fontSize:9},headStyles:{fillColor:[36,64,47]}});
    y=doc.lastAutoTable.finalY+18;
    const invRows=items.map(it=>{const t=totals(it.name);return [it.name,it.category||"",it.unit,t.inn,t.out,t.balance,it.reorder,t.balance<=Number(it.reorder||0)?"RESTOCK":"OK"];});
    doc.autoTable({startY:y,head:[["Item","Category","Unit","In","Out","Balance","Reorder","Status"]],body:invRows,theme:"grid",styles:{fontSize:8},headStyles:{fillColor:[36,64,47]}});
    doc.save(`St-Edward-Food-Store-${today()}.pdf`);
    showStatus("report-status","PDF report downloaded.");
    logAudit("Report exported","PDF report generated.");
  }catch(e){console.error(e);showStatus("report-status","Could not create PDF. Make sure the page has loaded fully.",true);}
}

/* ---------- Added: optional email delivery via EmailJS (Spark-plan friendly — no server needed) ----------
   To enable: create a free account at emailjs.com, then fill in EMAILJS_CONFIG below with your own
   Public Key, Service ID and Template ID. Until filled in, this silently does nothing — everything
   else in the app works exactly the same either way. */
const EMAILJS_CONFIG={publicKey:"",serviceId:"",templateId:""};
let emailjsReady=false;
function initEmailJS(){
  if(!EMAILJS_CONFIG.publicKey||typeof emailjs==="undefined")return;
  try{emailjs.init({publicKey:EMAILJS_CONFIG.publicKey});emailjsReady=true;}catch(e){console.warn("EmailJS init failed",e);}
}
async function sendLowStockEmail(lowItems){
  if(!emailjsReady||!appSettings.lowStockEmail||!EMAILJS_CONFIG.serviceId)return;
  const key="lowStockEmailSent:"+today();
  if(localStorage.getItem(key))return;
  try{
    await emailjs.send(EMAILJS_CONFIG.serviceId,EMAILJS_CONFIG.templateId,{
      to_email:appSettings.lowStockEmail,
      subject:"Food Store — low stock alert",
      message:lowItems.map(i=>`${i.name}: ${balance(i.name)} ${i.unit} (reorder at ${i.reorder})`).join("\n")
    });
    localStorage.setItem(key,"1");
  }catch(e){console.warn("Low-stock email failed",e);}
}

document.addEventListener("DOMContentLoaded",initEmailJS);
if(document.readyState!=="loading")initEmailJS();
if($("download-pdf-btn"))$("download-pdf-btn").onclick=exportPDF;
})();
